In [2]:
import numpy as np

## DataTypes and Attributes

In [3]:
# NumPy's main datatype is ndarray
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [4]:
type(a1)

numpy.ndarray

In [5]:
a2 = np.array([[1,2.0,3.3],
               [4,5,6.5]])

a3 = np.array([[[1,2,3],
               [4,5,6],
               [7,8,9]],
               [[10,11,12],
               [13,14,15],
               [16,17,18
               ]]])

In [6]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [7]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [8]:
a1.shape

(3,)

In [9]:
a2.shape

(2, 3)

In [10]:
a3.shape

(2, 3, 3)

In [11]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [12]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [13]:
a1.size, a2.size, a3.size # size tell how many element in array

(3, 6, 18)

In [14]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [15]:
# Create a DataFrame from a NumPy array
import pandas as pd

df = pd.DataFrame(a2)

In [16]:
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

In [17]:
df1 = pd.DataFrame(a3)

ValueError: Must pass 2-d input. shape=(2, 3, 3)

## Creating a Arrays

In [18]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [19]:
sample_array.dtype

dtype('int32')

In [20]:
ones = np.ones((2,3))

In [21]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [22]:
ones.shape

(2, 3)

In [23]:
ones.dtype

dtype('float64')

In [24]:
type(ones)

numpy.ndarray

In [25]:
zeroes = np.zeros((2,3))

In [26]:
zeroes


array([[0., 0., 0.],
       [0., 0., 0.]])

In [27]:
type(zeroes)

numpy.ndarray

In [28]:
zeroes.dtype

dtype('float64')

In [29]:
range_array = np.arange(0,10,2) # start=0, stop=10, step=2
range_array

array([0, 2, 4, 6, 8])

In [30]:
random_array = np.random.randint(0,10,size=(3,5))
random_array

array([[6, 3, 4, 0, 8],
       [6, 6, 8, 1, 5],
       [3, 2, 1, 5, 6]])

In [31]:
random_array.size

15

In [32]:
random_array.shape

(3, 5)

In [33]:
random_array2=np.random.random((5,3))
random_array2

array([[0.74737834, 0.09013411, 0.92260643],
       [0.7941508 , 0.75158688, 0.60326724],
       [0.5498092 , 0.81346558, 0.41282357],
       [0.82377241, 0.05479214, 0.54323436],
       [0.27051299, 0.95513625, 0.08790493]])

In [34]:
random_array2.shape

(5, 3)

In [35]:
random_array3 = np.random.rand(5,3)
random_array3

array([[0.40254272, 0.61867771, 0.65626277],
       [0.44137169, 0.56449996, 0.16208953],
       [0.61324763, 0.61315315, 0.35026966],
       [0.22772611, 0.0009234 , 0.13999032],
       [0.87463446, 0.63881618, 0.71850405]])

In [36]:
#Pseudo-random numbers
np.random.seed(seed=0) #there is not any change in the arrayn if seed =0
random_array4 = np.random.randint(10,size=(5,3))
random_array4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [37]:
random_array4.shape

(5, 3)

In [38]:
np.random.seed(seed=7)
random_array5 = np.random.random((5,3))
random_array5


array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [39]:
random_array5 = np.random.random((5,3))
random_array5

array([[0.90959353, 0.21338535, 0.45212396],
       [0.93120602, 0.02489923, 0.60054892],
       [0.9501295 , 0.23030288, 0.54848992],
       [0.90912837, 0.13316945, 0.52341258],
       [0.75040986, 0.66901324, 0.46775286]])

## Viewing Arrays and Metrices

In [40]:
np.unique(random_array4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
a1

array([1, 2, 3])

In [42]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [43]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [44]:
a1[0]

1

In [45]:
a2[0]

array([1. , 2. , 3.3])

In [46]:
a3.shape

(2, 3, 3)

In [47]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [49]:
a2[1]

array([4. , 5. , 6.5])

In [50]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [51]:
a3[:2,:2,:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [52]:
a4 = np.random.randint(10,size=(2,3,4,5))

In [53]:
a4

array([[[[6, 7, 7, 9, 3],
         [0, 7, 7, 7, 0],
         [5, 4, 3, 1, 3],
         [1, 3, 4, 3, 1]],

        [[9, 5, 9, 1, 2],
         [3, 2, 2, 5, 7],
         [3, 0, 9, 9, 3],
         [4, 5, 3, 0, 4]],

        [[8, 6, 7, 2, 7],
         [3, 8, 6, 6, 5],
         [6, 5, 7, 1, 5],
         [4, 4, 9, 9, 0]]],


       [[[6, 2, 6, 8, 2],
         [4, 1, 6, 1, 5],
         [1, 6, 9, 8, 6],
         [5, 9, 7, 5, 4]],

        [[9, 6, 8, 1, 5],
         [5, 8, 3, 7, 7],
         [9, 4, 7, 5, 9],
         [6, 2, 0, 5, 3]],

        [[0, 5, 7, 1, 8],
         [4, 9, 0, 2, 0],
         [7, 6, 2, 9, 9],
         [5, 1, 0, 0, 9]]]])

In [54]:
a4.shape

(2, 3, 4, 5)

In [55]:
a4.ndim

4

In [56]:
# Get the first 4 numbers of the inneer most arrays
a4[:,:,:,:4]

array([[[[6, 7, 7, 9],
         [0, 7, 7, 7],
         [5, 4, 3, 1],
         [1, 3, 4, 3]],

        [[9, 5, 9, 1],
         [3, 2, 2, 5],
         [3, 0, 9, 9],
         [4, 5, 3, 0]],

        [[8, 6, 7, 2],
         [3, 8, 6, 6],
         [6, 5, 7, 1],
         [4, 4, 9, 9]]],


       [[[6, 2, 6, 8],
         [4, 1, 6, 1],
         [1, 6, 9, 8],
         [5, 9, 7, 5]],

        [[9, 6, 8, 1],
         [5, 8, 3, 7],
         [9, 4, 7, 5],
         [6, 2, 0, 5]],

        [[0, 5, 7, 1],
         [4, 9, 0, 2],
         [7, 6, 2, 9],
         [5, 1, 0, 0]]]])

In [57]:
a4[:,:,:,:1]

array([[[[6],
         [0],
         [5],
         [1]],

        [[9],
         [3],
         [3],
         [4]],

        [[8],
         [3],
         [6],
         [4]]],


       [[[6],
         [4],
         [1],
         [5]],

        [[9],
         [5],
         [9],
         [6]],

        [[0],
         [4],
         [7],
         [5]]]])

## Manipulating & comparing arrays

### Arithmetic

In [58]:
a1

array([1, 2, 3])

In [59]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [60]:
ones=np.ones(3)
ones

array([1., 1., 1.])

In [61]:
#addition
a1 + ones

array([2., 3., 4.])

In [62]:
#substraction
a1-ones

array([0., 1., 2.])

In [63]:
#multiplication
a1*ones

array([1., 2., 3.])

In [64]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [65]:
a1*a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [66]:
a3


array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [67]:
a2*a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [68]:
a1

array([1, 2, 3])

In [69]:
a1*a3

array([[[ 1,  4,  9],
        [ 4, 10, 18],
        [ 7, 16, 27]],

       [[10, 22, 36],
        [13, 28, 45],
        [16, 34, 54]]])

In [70]:
# How can you reshape a2 to  be compatible with a3
# Search: "How we reshape numpy array"
a2*a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [ ]:
a1/ones

In [ ]:
a2 / a1

In [ ]:
# // floor division remove the decimal
a2//a1

In [ ]:
a2 ** 2

In [ ]:
np.square(a2)

In [ ]:
np.add(a1,ones)

In [ ]:
a1 % 2

In [ ]:
a1 /2

In [ ]:
np.exp(a1)

In [ ]:
np.log(a1)

### Aggregation 
Aggregation = performing the same operation on a number of things

In [ ]:
a_list = [1,2,3]
type(a_list)

In [ ]:
sum(a_list)

In [ ]:
type(a1)

In [ ]:
a1

In [ ]:
sum(a1)

In [ ]:
np.sum(a1)

use python's methods (`sum()`) on python datatypes and use NumPy's methods on NumPy arrays(`np.sum()`)

In [ ]:
# Creative a massive NumPy arrays
massive_array = np.random.random(100000)
massive_array.size

In [ ]:
massive_array[:100]

In [ ]:
%timeit sum(massive_array) # Pyhton's sum()
%timeit np.sum(massive_array) # NumPy's np.sum()

In [ ]:
a2

In [ ]:
np.mean(a2)

In [ ]:
np.max(a2)

In [ ]:
np.min(a2)

In [ ]:
# Standard deviation = a measure of how spread out a group of numbers is from the mean
np.std(a2)

In [ ]:
# Variance = measure of the average degree to which each number is different to the mean.
# Higher variance = wider range of numbers
# Lower variance = lower range of numbers
np.var(a2)

In [ ]:
# Standard deviation= squareroot of variance
np.sqrt(np.var(a2))

In [ ]:
# Demo of std and variance 
high_var_array = np.array([1,100,200,300,4000,5000])
low_var_array = np.array([2,4,6,8,10])

In [ ]:
high_var_array


In [ ]:
low_var_array

In [ ]:
np.var(high_var_array), np.var(low_var_array)

In [ ]:
np.std(high_var_array), np.std(low_var_array)

In [ ]:
np.mean(high_var_array), np.mean(low_var_array)

In [ ]:
%matplotlib inline
import matplotlib.pyplot as plt
plt.hist(high_var_array)
plt.show()

In [ ]:
plt.hist(low_var_array)
plt.show()

### Reshaping and Transposing  

In [ ]:
 a2

In [ ]:
a2.shape

In [ ]:
a3

In [ ]:
a3.shape

In [ ]:
a2 * a3

In [ ]:
a2.reshape(2,3,1)

In [ ]:
a2.reshape(2,3,1).shape

In [ ]:
a2_reshape = a2.reshape(2,3,1)

In [ ]:
a2_reshape

In [ ]:
a2_reshape * a3

In [71]:
#transpose = switches the axis
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [72]:
a2.shape

(2, 3)

In [73]:
a2.T

array([[1. , 4. ],
       [2. , 5. ],
       [3.3, 6.5]])

In [74]:
a2.T.shape

(3, 2)

In [75]:
a3.shape

(2, 3, 3)

In [76]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [77]:
a3.T


array([[[ 1, 10],
        [ 4, 13],
        [ 7, 16]],

       [[ 2, 11],
        [ 5, 14],
        [ 8, 17]],

       [[ 3, 12],
        [ 6, 15],
        [ 9, 18]]])

In [78]:
a3.T.shape

(3, 3, 2)

### Dot Product

In [79]:
np.random.seed(0)

mat1 = np.random.randint(10,size=(5,3))
mat2 = np.random.randint(10,size=(5,3))

mat1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [80]:
mat2

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]])

In [81]:
mat1.shape, mat2.shape


((5, 3), (5, 3))

In [82]:
# Element-wise multiplication (Hadamard product)
mat1*mat2

array([[30,  0, 21],
       [24,  7, 45],
       [27, 40, 18],
       [16, 21,  0],
       [24, 40,  0]])

In [83]:
# Dot Prodiuct
np.dot(mat1,mat2)

ValueError: shapes (5,3) and (5,3) not aligned: 3 (dim 1) != 5 (dim 0)

In [84]:
# Transpose mat1
mat1.T

array([[5, 3, 3, 4, 8],
       [0, 7, 5, 7, 8],
       [3, 9, 2, 6, 1]])

In [85]:
mat1.shape,mat2.T.shape

((5, 3), (3, 5))

In [86]:
mat3 = np.dot(mat1,mat2.T)
mat3

array([[ 51,  55,  72,  20,  15],
       [130,  76, 164,  33,  44],
       [ 67,  39,  85,  27,  34],
       [115,  69, 146,  37,  47],
       [111,  77, 145,  56,  64]])

In [87]:
mat3.shape

(5, 5)

### Dot product example (nut butter sales)

In [88]:
np.random.seed(0)
# Number of jars sold
sales_amounts = np.random.randint(20,size=(5,3))
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [89]:
# Create weekly_sales DataFrame
weekly_sales = pd.DataFrame(sales_amounts,index=["Mon","Tues","Wed","Thrus","Fri"],columns=["Almond butter","Peanut butter","Cashew butter"])
weekly_sales

Almond butter  Peanut butter  Cashew butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thrus              4              6             12
Fri                1              6              7

In [90]:
# Create Prices array
prices = np.array([10,8,12])
prices

array([10,  8, 12])

In [91]:
prices.shape

(3,)

In [92]:
#Create butter_prices Dataframe
butter_prices = pd.DataFrame(prices.reshape(1,3),index=["Price"],columns=["Almond butter","Peanut butter","Cashew butter"])
butter_prices

Almond butter  Peanut butter  Cashew butter
Price             10              8             12

In [93]:
prices

array([10,  8, 12])

In [94]:
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [95]:
prices.shape, sales_amounts.shape

((3,), (5, 3))

In [96]:
total_prices = prices.dot(sales_amounts)

ValueError: shapes (3,) and (5,3) not aligned: 3 (dim 0) != 5 (dim 0)

In [97]:
# Shapes are not aligned lets transpose

In [98]:
total_sales = prices.dot(sales_amounts.T)
total_sales

array([240, 138, 458, 232, 142])

In [99]:
# Craete Daily Sales
butter_prices.shape, weekly_sales.shape

((1, 3), (5, 3))

In [100]:
weekly_sales

Almond butter  Peanut butter  Cashew butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thrus              4              6             12
Fri                1              6              7

In [101]:
daily_sales = butter_prices.dot(weekly_sales.T)
daily_sales

Mon  Tues  Wed  Thrus  Fri
Price  240   138  458    232  142

In [102]:
# not work beacuse the shape is not right shape
weekly_sales["Total ($)"] = daily_sales
weekly_sales

ValueError: Expected a 1D array, got an array with shape (5, 5)

In [103]:
daily_sales.shape

(1, 5)

In [104]:
weekly_sales.shape

(5, 3)

In [105]:
weekly_sales["Total ($)"] = daily_sales.T
weekly_sales

Almond butter  Peanut butter  Cashew butter  Total ($)
Mon               12             15              0        240
Tues               3              3              7        138
Wed                9             19             18        458
Thrus              4              6             12        232
Fri                1              6              7        142

### Comparison Operators

In [106]:
a1

array([1, 2, 3])

In [107]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [108]:
a1 > a2

array([[False, False, False],
       [False, False, False]])

In [110]:
bool_array =a1 >= a2
bool_array

array([[ True,  True, False],
       [False, False, False]])

In [112]:
type(bool_array), bool_array.dtype

(numpy.ndarray, dtype('bool'))

In [113]:
a1 > 5

array([False, False, False])

In [114]:
a1 < 5

array([ True,  True,  True])

In [115]:
a1 == a1

array([ True,  True,  True])

In [116]:
a1

array([1, 2, 3])

In [117]:
a1 == a2

array([[ True,  True, False],
       [False, False, False]])

## Sorting Arrays

In [121]:
random_array


array([[7, 8, 1, 5, 9],
       [8, 9, 4, 3, 0],
       [3, 5, 0, 2, 3]])

In [122]:
np.sort(random_array)

array([[1, 5, 7, 8, 9],
       [0, 3, 4, 8, 9],
       [0, 2, 3, 3, 5]])

In [123]:
random_array

array([[7, 8, 1, 5, 9],
       [8, 9, 4, 3, 0],
       [3, 5, 0, 2, 3]])

In [124]:
np.argsort(random_array) # show the index of element

array([[2, 3, 0, 1, 4],
       [4, 3, 2, 0, 1],
       [2, 3, 0, 4, 1]], dtype=int64)

In [125]:
a1

array([1, 2, 3])

In [126]:
np.argsort(a1)

array([0, 1, 2], dtype=int64)

In [128]:
np.argmin(a1) #return the min val index

0

In [131]:
np.argmax(random_array,axis=0) # return the max number index in the col

array([1, 1, 1, 0, 0], dtype=int64)

In [130]:
random_array

array([[7, 8, 1, 5, 9],
       [8, 9, 4, 3, 0],
       [3, 5, 0, 2, 3]])

In [132]:
np.argmax(random_array,axis=1) # retuurn the index of the highest number in row 

array([4, 1, 1], dtype=int64)

## Pratical Example - NumPy

<img src ="numpy-images/panda.png"/>

In [138]:
# Turn an image into a NumPy array
from matplotlib.image import imread

panda = imread("numpy-images/panda.png")
panda

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       ...,

       [[0.13333334, 0.07450981, 0.05490196],
        [0.12156863, 0.0627451 , 0.04313726],
        [0.10980392, 0

In [140]:
print(type(panda))

<class 'numpy.ndarray'>


In [143]:
panda.size, panda.shape, panda.ndim

(24465000, (2330, 3500, 3), 3)

In [144]:
panda[:100]

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       ...,

       [[0.06666667, 0.12156863, 0.07058824],
        [0.06666667, 0.12156863, 0.07058824],
        [0.06666667, 0

In [145]:
panda[:5]

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.

<img src="numpy-images/car-photo.png"/>

In [146]:
car = imread("numpy-images/car-photo.png")
print(type(car))

<class 'numpy.ndarray'>


In [147]:
car[:1]

array([[[0.5019608 , 0.50980395, 0.4862745 , 1.        ],
        [0.3372549 , 0.34509805, 0.30588236, 1.        ],
        [0.20392157, 0.21568628, 0.14901961, 1.        ],
        ...,
        [0.64705884, 0.7058824 , 0.54901963, 1.        ],
        [0.59607846, 0.63529414, 0.45882353, 1.        ],
        [0.44705883, 0.47058824, 0.3372549 , 1.        ]]], dtype=float32)

# Dog
<img src="numpy-images/dog-photo.png" />

In [148]:
dog = imread("numpy-images/dog-photo.png")
print(type(dog))

<class 'numpy.ndarray'>


In [149]:
dog[:1]

array([[[0.70980394, 0.80784315, 0.88235295, 1.        ],
        [0.72156864, 0.8117647 , 0.8862745 , 1.        ],
        [0.7411765 , 0.8156863 , 0.8862745 , 1.        ],
        ...,
        [0.49803922, 0.6862745 , 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8352941 , 1.        ]]], dtype=float32)

In [150]:
dog

array([[[0.70980394, 0.80784315, 0.88235295, 1.        ],
        [0.72156864, 0.8117647 , 0.8862745 , 1.        ],
        [0.7411765 , 0.8156863 , 0.8862745 , 1.        ],
        ...,
        [0.49803922, 0.6862745 , 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8352941 , 1.        ]],

       [[0.69411767, 0.8039216 , 0.8862745 , 1.        ],
        [0.7019608 , 0.8039216 , 0.88235295, 1.        ],
        [0.7058824 , 0.80784315, 0.88235295, 1.        ],
        ...,
        [0.5019608 , 0.6862745 , 0.84705883, 1.        ],
        [0.49411765, 0.68235296, 0.84313726, 1.        ],
        [0.49411765, 0.68235296, 0.8392157 , 1.        ]],

       [[0.6901961 , 0.8       , 0.88235295, 1.        ],
        [0.69803923, 0.8039216 , 0.88235295, 1.        ],
        [0.7058824 , 0.80784315, 0.88235295, 1.        ],
        ...,
        [0.5019608 , 0.6862745 , 0.84705883, 1.        ],
        [0.49803922, 0.686274

In [151]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1, 100, 10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])